# -*- coding: utf-8 -*-
"""MySolution.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t1Rj97pBiY1ULgynOr9eouF3EyPP8m_s
"""

import pandas as pd

df=pd.read_excel('employee__1_.xls',index_col='Emp ID')

df['Date of Birth']=pd.to_datetime(df['Date of Birth'])
df['Date of Joining']=pd.to_datetime(df['Date of Joining'])

df['Employee Name']=df['First Name']+' '+df['Last Name']

df=df.sort_values("Date of Birth")

df=df[['Employee Name','Quarter of Joining']]

d = {}
for i in df['Quarter of Joining'].unique():
    d[i] = [df['Employee Name'][j] for j in df[df['Quarter of Joining']==i].index]

print(d)